### ISSUE TITLE
force timestamp

### ISSUE THREAD

**Issue by zacksiri** [palkan/influxer#13]
It would be cool to be able to override the timestamp of the point.

Sometimes we need to process historical data and want to plot it with past dates, is this possible with influxer?

**Comment by palkan** [comment]
Yes, it's possible. By default each _Metrics_ has _timestamp_ attribute (since version 0.4.0, prior versions use old _time_ name).

So you can write something like:

```ruby
MyMetrics.new(timestamp: ts).write
```

But it's not very efficient if you want to batch process data. It's better to use [influxdb-ruby](https://github.com/influxdata/influxdb-ruby) itself.
E.g. using Influxer API:

```ruby
data = [
  {
    series: 'cpu',
    tags: { host: 'server_1', regios: 'us' },
    values: {internal: 5, external: 0.453345, time: 1458585171}
  },
  {
    series: 'gpu',
    values: {value: 0.9999, time: 1458585171},
  }
]

Influxer.client.write_points(data)
```

**Comment by rodrigoapereira** [comment]
Hello @palkan.
I'm using InfluxDB v0.10, this version expects the timestamp is separated from values.
I tried your suggestion but it did not work, the influx ignores the timestamp that was placed and creates an attribute to it.

```json
{
    "results": [
        {
            "series": [
                {
                    "name": "testing",
                    "columns": [
                        "time",
                        "test_id",
                        "timestamp",
                        "value"
                    ],
                    "values": [
                        [
                            "2016-03-21T23:00:05Z",
                            "10",
                            1458601195,
                            10
                        ]
                    ]
                }
            ]
        }
    ]
}
```

Please view this PR #16.

**Comment by palkan** [comment]
Sorry, didn't notice this change in 0.10.

Then this should work:

```ruby
data = [
  {
    series: 'cpu',
    tags: { host: 'server_1', regios: 'us' },
    values: {internal: 5, external: 0.453345},
    timestamp: 1458585171
  },
  {
    series: 'gpu',
    values: {value: 0.9999},
    timestamp: 1458585171
  }
]

Influxer.client.write_points(data)
```

**Comment by palkan** [comment]
Influxer updated to 0.5.0 with actual timestamp support.
