### ISSUE TITLE
ArgumentError railse if the influxdb is not reachable.

### ISSUE THREAD

**Issue by hirakiuc** [palkan/influxer#22]
Hi, thank you for your great gem! 😄 

But I found an issue as is the title.

# gem versions

- influxer 0.5.1
- influxdb 0.3.6

# Model definition

```
class Target < ApplicationRecord
  hsa_metrics :metrics
end

class TargetMetrics < Influxer::Metrics
  set_series :cpu
  tags :target_id
  attributes :value, :kind
end
```

(I removed some codes..., sorry.)

# How to reproduce?

1. Stop your influxDB.
2. send a request just like below.

```
irb(main):001:0> target = Target.last
  Target Load (0.3ms)  SELECT  `targets`.* FROM `targets` ORDER BY `targets`.`id` DESC LIMIT 1
=> #<Target id: "i-xxxxxx", name: "web server", group_id: 2, type_id: 41, created_at: "2016-08-11 01:37:11", updated_at: "2016-08-11 01:37:11">
irb(main):002:0> target.metrics
ArgumentError: wrong number of arguments (given 2, expected 1)
        from /Users/hirakiuc/Desktop/github_repos/watchtower/.bundle/ruby/2.3.0/gems/influxer-0.5.1/lib/influxer/rails/client.rb:15:in `log'
        from /Users/hirakiuc/Desktop/github_repos/watchtower/.bundle/ruby/2.3.0/gems/influxdb-0.3.6/lib/influxdb/client/http.rb:59:in `rescue in connect_with_retry'
        from /Users/hirakiuc/Desktop/github_repos/watchtower/.bundle/ruby/2.3.0/gems/influxdb-0.3.6/lib/influxdb/client/http.rb:68:in `connect_with_retry'
 
(...snipped...)
``` 

# What is the problem?

I think that this problem will resolve if Influxer renames [Influxer::Client#log](https://github.com/palkan/influxer/blob/master/lib/influxer/rails/client.rb#L15) method or Influxer::Client does not inherit InfluxDB::Client. 

Here is my thought.

---
Influxer use [influxdb-ruby](https://github.com/influxdata/influxdb-ruby) internaly.

When http request timeout occured, [this code](https://github.com/influxdata/influxdb-ruby/blob/master/lib/influxdb/client/http.rb#L59) is executed to log error message in [influxdb-ruby](https://github.com/influxdata/influxdb-ruby).

But Influxer defines [same name method](https://github.com/palkan/influxer/blob/master/lib/influxer/rails/client.rb#L15) which require only one argument in the same namespace.

So it seems like Influxer override `log` method which requires one argument, and Influxdb-ruby calls the `log` method with two arguments.

Finally, ArgumentError raised.  

---

**Comment by palkan** [comment]
Thanks for the report!

Wow, that was me, who add `log/2` to [influxdb-ruby](https://github.com/influxdata/influxdb-ruby/blame/master/lib/influxdb/client/http.rb#L59) during refactoring 😮

Ok, I gonna made a quick fix.

**Comment by palkan** [comment]
Fixed. Version 0.5.2
