### ISSUE TITLE
Influxer::WhereClause#build_range error for negate=true case

### ISSUE THREAD

**Issue by Martin288** [palkan/influxer#23]
the source code in https://github.com/palkan/influxer/blob/master/lib/influxer/metrics/relation/where_clause.rb#L60-L66 shows:

```ruby
    def build_range(key, val, negate)
      if negate
        # FIX: the below maybe `or` instead of `and`  ???
        "#{key} < #{quoted(val.begin)} and #{key} > #{quoted(val.end)}"
      else
        "#{key} > #{quoted(val.begin)} and #{key} < #{quoted(val.end)}"
      end
    end
```

I didn't fork your repo and just reading your codes, I can fork it and send a new PR if needed.

**Comment by palkan** [comment]
Thanks! You're definitely right, there should be "or". I'll fix it immediately.
