### ISSUE TITLE
Is it a plan to enable setting time precision for models?

### ISSUE THREAD

**Issue by Martin288** [palkan/influxer#24]
Currently models use default influxdb time precision, that is, ns to write point. But InfluxDB supports different time precision for different measurements so I think it is better to provide this option in influxer.

**Comment by palkan** [comment]
It has alway been there (see https://github.com/palkan/influxer/blob/master/lib/influxer/config.rb#L30).
And here is the [wiki article](https://github.com/palkan/influxer/wiki/Getting-Started#configuration) on configuration.

**Comment by Martin288** [comment]
@palkan ok, thanks
