### ISSUE TITLE
Rails 3 support

### ISSUE THREAD

**Issue by gjhenrique** [palkan/influxer#26]
Hi.

First of all, thanks for the amazing library.

Would you like to support rails 3 or is it too old?

I'm working on that right now if you are interested.

**Comment by palkan** [comment]
Hi!

Well, Rails 3 is old) Let's look how difficult it would be to support it. Feel free to PR.

**Comment by gjhenrique** [comment]
Nice to hear that!!!

I'll open a PR soon.
It's not so difficult...=)

Thanks.
