### ISSUE TITLE
Anyway update bug with influxer config

### ISSUE THREAD

**Issue by nofxx** [palkan/influxer#32]
Hello palkan,

I'm trying to debug anyway_config 1.1.3 update:

```
wrong number of arguments (given 1, expected 0)
influxer (1.1.1) lib/influxer/config.rb:35:in `load'
anyway_config (1.1.3) lib/anyway/config.rb:69:in `initialize'
```
Do we need `def load` on influxer anymore?
Thank you for both gems =D

**Comment by palkan** [comment]
Thanks for catching that!

Fixed and released as 1.1.2.
