### ISSUE TITLE
ERR: invalid expression: 1 = 0

### ISSUE THREAD

**Issue by dimiii** [palkan/influxer#41]
This may happen, when a custom scope is used, MWE:

```
scope :boom!, -> { where(time: []) }
```
It generates an incorrect query:

> select * from year.trace where 1 = 0
ERR: invalid expression: 1 = 0

Probably, for influxdb `time < 0` will be better than `1 = 0` as a clause returning none.

**Comment by palkan** [comment]
Which version of InfluxDB you use?

> Probably, for influxdb time < 0 will be better than 1 = 0 as a clause returning none.

Would you like to propose a PR?

**Comment by dimiii** [comment]
That was with Invluxdb v1.4.2.  Sure, I can propose a PR for your consideration.

**Comment by dimiii** [comment]
Well, I've investigated this question for influxdb v1.2.4 and v1.4.2, for correct inference measurements with data are required.  For the old version instance: 
```
> precision rfc3339
> select current_reading from daily.bandwidth limit 1
name: bandwidth
time                 current_reading
----                 ---------------
2018-03-12T00:00:00Z 4.9496644288e+08
```

It accepts query in syntax:
```
> select current_reading from daily.bandwidth where 1 = 0 limit 1
```
But does not always process it correctly:
```
> select current_reading from daily.bandwidth where 1 <> 0 limit 1
# returns nothing
```
Comparing to

```
> select current_reading from daily.bandwidth where time < 0 limit 1
> select current_reading from daily.bandwidth where time >= 0 limit 1
name: bandwidth
time                 current_reading
----                 ---------------
2018-03-12T00:00:00Z 4.9496644288e+08
```
---
For the v1.4.2 instance:
```
> select current_reading from daily.power_load_amps limit 1
name: power_load_amps
time                 current_reading
----                 ---------------
2018-03-13T13:00:00Z 3.6
```
all is worse:
```
> select current_reading from daily.power_load_amps where 1 = 0 limit 1
ERR: invalid expression: 1 = 0
> select current_reading from daily.power_load_amps where 1 <> 0 limit 1
ERR: invalid expression: 1 != 0
```
Workaround with 'time < 0' still works:
```
> select current_reading from daily.power_load_amps where time < 0 limit 1
> select current_reading from daily.power_load_amps where time >= 0 limit 1
name: power_load_amps
time                 current_reading
----                 ---------------
2018-03-13T13:00:00Z 3.6

> select current_reading from daily.power_load_amps where time >= 0 and outlet = 'total' and time = '2018-03-13T13:00:00Z' limit 1
name: power_load_amps
time                 current_reading
----                 ---------------
2018-03-13T13:00:00Z 3.6
```
I do not actually like this workaround, but an alternative is registration of yet another bug in influxdb's issue tracker, and it's well known how crappy is their query language and its processing.

**Comment by dimiii** [comment]
Now I see I needed scoping by time, but it just does not work for influxdb, LOL: 
https://docs.influxdata.com/influxdb/v1.4/troubleshooting/frequently-asked-questions/#why-is-my-query-with-a-where-or-time-clause-returning-empty-results

So, for me #41 is not critical.
