### ISSUE TITLE
How to write data through UDP？

### ISSUE THREAD

**Issue by scriptfans** [palkan/influxer#45]
thanks.

**Comment by palkan** [comment]
We use `influxdb-ruby` under the hood, so check their readme https://github.com/influxdata/influxdb-ruby#writing-data.

In Influxer you should change the configuration. For example:

```ruby
Influxer.configure do |config|
  config.udp = { host: "127.0.0.1", port: 4444 }
end
```

**Comment by scriptfans** [comment]
@palkan thanks very much. can I change the configuration through the influxdb.yml?
`
production:
  udp:
    host: localhost
    port: 4444
`
And is there any change in saving api? Does it automatically use udp to send data point?

**Comment by palkan** [comment]
Yeah, you can use `influxdb.yml`

> And is there any change in saving API? Does it automatically use UDP to send data point?

No change required
