### ISSUE TITLE
Influxer client does work with anyway config 2.1.0

### ISSUE THREAD

**Issue by jklimke** [palkan/influxer#52]
## What did you do?

A bundle update command updated anyway_Config to 2.1.0

## What did you expect to happen?

Config should work as before or the gem should not be automatically updated

## What actually happened?

The anyway config interface seems to have changes so that the initilization of the client config does not use the values defined in ```config/influx.yml``` in rails

## Environment

**Ruby Version:**
2.7.2

**Influxer Version:**
2.2.2

**Comment by palkan** [comment]
Duplicate #53
