### ISSUE TITLE
Influxer Client does not work with anyway_config 2.1.0

### ISSUE THREAD

**Issue by jklimke** [palkan/influxer#53]
## What did you do?

A bundle update command updated anyway_Config to 2.1.0

## What did you expect to happen?

Config should work as before or the gem should not be automatically updated

## What actually happened?

The anyway config interface seems to have changes so that the initilization of the client config does not use the values defined in ```config/influx.yml``` in rails

## Environment

**Ruby Version:**
2.7.2

**Influxer Version:**
2.2.2

**Comment by AlexanderShvaykin** [comment]
@jklimke I was not able to reproduce your problem. Can you send an example of a configuration that stopped loading?

**Comment by jklimke** [comment]
I tracked down the problem a little more. I debugged into the influxer client initialization. 

The Influxer Client seems to use as_json on Influxer.config to get access to a hash of configuration values.

```
module Influxer
  # InfluxDB API client
  class Client < ::InfluxDB::Client
    def initialize
      super(nil, Influxer.config.as_json.symbolize_keys!)
    end
```

When debugging, the config values themselves are loaded as inspected. It seems that the configuration values itself are contained in an "values" entry within this hash. It might be sufficent to scope into the "values" entry an pass that to the super call of influxer client.

Example of the ```Influxer.config.as_json``` call. 

```Influxer.config.as_json
{"config_name"=>"influxdb", "env_prefix"=>"INFLUXDB", "values"=>{"database"=>"<database_name>", "time_precision"=>"ns", "time_duration_suffix_enabled"=>false, "host"=>"localhost", "port"=>"8086", "username"=>"<username>", "password"=>"<password>", "cache_enabled"=>true, "cache"=>{"expires_in"=>30}}, "__trace__"=>{"type"=>"trace", "source"=>{}, "value"=>{"database"=>{"type"=>"value", "source"=>{"type"=>"yml", "path"=>"config/influxdb.yml"}, "value"=>"<database_name>"}, "time_precision"=>{"type"=>"value", "source"=>{"type"=>"defaults"}, "value"=>"ns"}, "time_duration_suffix_enabled"=>{"type"=>"value", "source"=>{"type"=>"defaults"}, "value"=>false}, "host"=>{"type"=>"value", "source"=>{"type"=>"yml", "path"=>"config/influxdb.yml"}, "value"=>"localhost"}, "port"=>{"type"=>"value", "source"=>{"type"=>"yml", "path"=>"config/influxdb.yml"}, "value"=>"8086"}, "username"=>{"type"=>"value", "source"=>{"type"=>"yml", "path"=>"config/influxdb.yml"}, "value"=>"<username>"}, "password"=>{"type"=>"value", "source"=>{"type"=>"yml", "path"=>"config/influxdb.yml"}, "value"=>"<password>"}, "cache_enabled"=>{"type"=>"value", "source"=>{"type"=>"yml", "path"=>"config/influxdb.yml"}, "value"=>false}, "cache"=>{"type"=>"trace", "source"=>{}, "value"=>{"expires_in"=>{"type"=>"value", "source"=>{"type"=>"yml", "path"=>"config/influxdb.yml"}, "value"=>30}}}}}}```
