### ISSUE TITLE
ActiveSupport::PerThreadRegistry is deprecated

### ISSUE THREAD

**Issue by jjohnson** [palkan/influxer#55]
https://github.com/palkan/influxer/blob/94f9a03ba9a88eb49b41b33536c432912daadda9/lib/influxer/metrics/scoping/current_scope.rb#L17-L19

```
DEPRECATION WARNING: ActiveSupport::PerThreadRegistry is deprecated and will be removed in Rails 7.1.
Use `Module#thread_mattr_accessor` instead.
```

**Comment by AlexanderShvaykin** [comment]
Thanks. I hope I can find time to fix this in the near future.
