### ISSUE TITLE
Ability to conncet to multiple databases/hosts

### ISSUE THREAD

**Issue by stony245** [palkan/influxer#57]
I have 3 processes that write into 3 databases on one host in an existing application (solaranzeige,de).

I want to summarize the data from these 3 processes (sum up power in watts, current in amperes and so on) and then write the data  to another influx database with the same structure on another host, where Grafana is running.

As the standard ActiveRecord things like 
`  self.abstract_class = true`
`  establish_connection :central`

do not work: How can I proceed to work with these 4 databases?

**Comment by palkan** [comment]
There is no such DSL (at least, yet), but you can achieve this by overriding the `#client` method for your Metrics class: https://github.com/palkan/influxer/blob/e01d37e86c51b06445c8dbf0c7cb3fe15b13ed20/lib/influxer/metrics/metrics.rb#L195-L197

**Comment by stony245** [comment]
Thank you. Do you have a short example, how to implement this?
```
class NetLocal1
   xxxx
end

class NetLocal2
   xxxx
end

class NetCentral
   xxxx
end
```
