### ISSUE TITLE
Could handle errors like InfluxDB::Error: Couldn't find series: ?

### ISSUE THREAD

**Issue by ceritium** [palkan/influxer#8]
Before write a point I want query Metric.all without raise `InfluxDB::Error: Couldn't find series...`

**Comment by palkan** [comment]
Yeah, I know about this problem.
This functionality must be implemented within `influxdb-ruby` gem; Influxer doesn't deal with raw API response.

I'm going to get rid of influxdb-ruby during the upgrade to support InfluxDB 0.9. I'm waiting for the final release.

**Comment by palkan** [comment]
I've proposed a [PR](https://github.com/influxdb/influxdb-ruby/pull/88) to `influxdb-ruby` which adds support for detecting `couldn't find series` as special kind of error.

**Comment by ceritium** [comment]
Merged right? :D
