### ISSUE TITLE
Bugs in wiki

### ISSUE THREAD

**Issue by ceritium** [palkan/influxer#9]
## build

```ruby
point2 = MyMetrics.build user_id: 1, load_time: 0
``` 

`MyMetrics` do not respond to `build` but yes to `new`. `build` is just for `Influxer::Relations`

Found in https://github.com/palkan/influxer/wiki/Getting-Started#write-data-points

## write!

Found in https://github.com/palkan/influxer/wiki/ActiveRecord-integration and https://github.com/palkan/influxer/wiki/Getting-Started#write-data-points

I tried to use `write!` for `Influxer::Relations` and for  `Influxer::Metrics` objects but raise `NoMethodError`, instead I can use without problem `write`.

**Comment by palkan** [comment]
Fixed. Thanks!
